// <auto-generated />
using Cooxboox.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cooxboox.PostgreSQL.Migrations
{
    [DbContext(typeof(CooxbooxContext))]
    partial class CooxbooxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cooxboox.Infrastructure.Entities.KitchenEntity", b =>
                {
                    b.Property<int>("KitchenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KitchenId"));

                    b.Property<string>("Confidentiality")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("KitchenId");

                    b.HasIndex("Confidentiality");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StreamId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Kitchens", "Cooxboox");
                });

            modelBuilder.Entity("Cooxboox.Infrastructure.Entities.KitchenLocaleEntity", b =>
                {
                    b.Property<int>("KitchenLocaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KitchenLocaleId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PublishedVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("KitchenLocaleId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Language");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("PublishedOn");

                    b.HasIndex("PublishedVersion");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("KitchenId", "Language")
                        .IsUnique();

                    b.ToTable("KitchenLocales", "Cooxboox");
                });

            modelBuilder.Entity("Cooxboox.Infrastructure.Entities.PublishedKitchenLocaleEntity", b =>
                {
                    b.Property<int>("KitchenLocaleId")
                        .HasColumnType("integer");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("KitchenLocaleId");

                    b.HasIndex("Language");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("PublishedOn");

                    b.HasIndex("Version");

                    b.HasIndex("KitchenId", "Language")
                        .IsUnique();

                    b.ToTable("PublishedKitchenLocales", "Cooxboox");
                });

            modelBuilder.Entity("Cooxboox.Infrastructure.Entities.KitchenLocaleEntity", b =>
                {
                    b.HasOne("Cooxboox.Infrastructure.Entities.KitchenEntity", "Kitchen")
                        .WithMany("Locales")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("Cooxboox.Infrastructure.Entities.PublishedKitchenLocaleEntity", b =>
                {
                    b.HasOne("Cooxboox.Infrastructure.Entities.KitchenEntity", "Kitchen")
                        .WithMany("PublishedLocales")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooxboox.Infrastructure.Entities.KitchenLocaleEntity", "KitchenLocale")
                        .WithOne("PublishedLocale")
                        .HasForeignKey("Cooxboox.Infrastructure.Entities.PublishedKitchenLocaleEntity", "KitchenLocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitchen");

                    b.Navigation("KitchenLocale");
                });

            modelBuilder.Entity("Cooxboox.Infrastructure.Entities.KitchenEntity", b =>
                {
                    b.Navigation("Locales");

                    b.Navigation("PublishedLocales");
                });

            modelBuilder.Entity("Cooxboox.Infrastructure.Entities.KitchenLocaleEntity", b =>
                {
                    b.Navigation("PublishedLocale");
                });
#pragma warning restore 612, 618
        }
    }
}
