name: cooxboox_api
services:
  cooxboox_api:
    build:
      context: .
      dockerfile: /src/Cooxboox/Dockerfile
    image: cooxboox_api
    container_name: Cooxboox_api
    restart: unless-stopped
    environment:
      ASPNETCORE_Environment: Development
    ports:
      - 8100:8080
